// mangacount.client/src/app/features/collection/add-entry-modal/add-entry-modal.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { EntryService } from '../../../core/services/entry.service';
import { MangaService } from '../../../core/services/manga.service';
import { Entry, EntryCreateDto } from '../../../models/entry.model';
import { Manga } from '../../../models/manga.model';
import { Profile } from '../../../models/profile.model';

@Component({
  selector: 'app-add-entry-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './add-entry-modal.component.html',
  styleUrls: ['./add-entry-modal.component.css']
})
export class AddEntryModalComponent implements OnInit {
  @Input() isOpen = false;
  @Input() mangas: Manga[] = [];
  @Input() selectedProfile: Profile | null = null;
  @Input() editingEntry: Entry | null = null;
  @Output() close = new EventEmitter<void>();
  @Output() success = new EventEmitter<void>();

  entry: EntryCreateDto = {
    mangaId: 0,
    profileId: 0,
    quantity: 0,
    pending: '',
    priority: false
  };

  selectedMangaName = '';
  isCreatingNewManga = false;

  constructor(
    private entryService: EntryService,
    private mangaService: MangaService
  ) {}

  ngOnInit(): void {
    if (this.editingEntry) {
      this.entry = {
        id: this.editingEntry.id,
        mangaId: this.editingEntry.mangaId,
        profileId: this.editingEntry.profileId,
        quantity: this.editingEntry.quantity,
        pending: this.editingEntry.pending || '',
        priority: this.editingEntry.priority
      };
      this.selectedMangaName = this.editingEntry.manga.name;
    } else {
      this.resetForm();
    }
  }

  resetForm(): void {
    this.entry = {
      mangaId: 0,
      profileId: this.selectedProfile?.id || 0,
      quantity: 0,
      pending: '',
      priority: false
    };
    this.selectedMangaName = '';
    this.isCreatingNewManga = false;
  }

  onMangaSelect(mangaId: string): void {
    const id = parseInt(mangaId);
    if (id > 0) {
      this.entry.mangaId = id;
      this.isCreatingNewManga = false;
      const selectedManga = this.mangas.find(m => m.id === id);
      this.selectedMangaName = selectedManga?.name || '';
    } else {
      this.entry.mangaId = 0;
      this.isCreatingNewManga = true;
    }
  }

  onSubmit(): void {
    if (!this.selectedProfile) return;

    if (this.isCreatingNewManga && this.selectedMangaName.trim()) {
      // Create new manga first
      const newManga = {
        name: this.selectedMangaName.trim(),
        volumes: null,
        formatId: 1, // Default format
        publisherId: 1 // Default publisher
      };

      this.mangaService.createOrUpdateManga(newManga).subscribe({
        next: (manga: any) => {
          this.entry.mangaId = manga.id;
          this.saveEntry();
        },
        error: (error: any) => console.error('Error creating manga', error)
      });
    } else if (this.entry.mangaId > 0) {
      this.saveEntry();
    }
  }

  private saveEntry(): void {
    this.entryService.createOrUpdateEntry(this.entry).subscribe({
      next: () => {
        this.success.emit();
        this.onClose();
      },
      error: (error: any) => console.error('Error saving entry', error)
    });
  }

  onClose(): void {
    this.resetForm();
    this.close.emit();
  }
}

<div class="modal-overlay" *ngIf="isOpen" (click)="onClose()">
  <div class="modal" (click)="$event.stopPropagation()">
    <div class="modal-header">
      <h2>{{ editingEntry ? 'Editar Entrada' : 'Agregar Entrada' }}</h2>
      <button class="close-btn" (click)="onClose()">✕</button>
    </div>

    <form (ngSubmit)="onSubmit()" class="modal-body">
      <div class="form-group">
        <label for="manga">Manga:</label>
        <select 
          id="manga" 
          [value]="entry.mangaId" 
          (change)="onMangaSelect($any($event.target).value)"
          class="form-control">
          <option value="0">-- Crear nuevo manga --</option>
          <option *ngFor="let manga of mangas" [value]="manga.id">
            {{ manga.name }}
          </option>
        </select>
      </div>

      <div class="form-group" *ngIf="isCreatingNewManga">
        <label for="mangaName">Nombre del nuevo manga:</label>
        <input 
          type="text" 
          id="mangaName"
          [(ngModel)]="selectedMangaName"
          name="mangaName"
          class="form-control"
          placeholder="Ingresa el nombre del manga">
      </div>

      <div class="form-group">
        <label for="quantity">Cantidad de volúmenes:</label>
        <input 
          type="number" 
          id="quantity"
          [(ngModel)]="entry.quantity"
          name="quantity"
          min="0"
          class="form-control">
      </div>

      <div class="form-group">
        <label for="pending">Volúmenes pendientes (opcional):</label>
        <input 
          type="text" 
          id="pending"
          [(ngModel)]="entry.pending"
          name="pending"
          class="form-control"
          placeholder="ej. Volúmenes 5-10">
      </div>

      <div class="form-group">
        <label class="checkbox-label">
          <input 
            type="checkbox" 
            [(ngModel)]="entry.priority"
            name="priority">
          <span class="checkmark"></span>
          Marcar como prioritario
        </label>
      </div>

      <div class="form-actions">
        <button 
          type="submit" 
          class="save-btn"
          [disabled]="(!entry.mangaId && !selectedMangaName.trim())">
          {{ editingEntry ? 'Actualizar' : 'Guardar' }}
        </button>
        <button type="button" (click)="onClose()" class="cancel-btn">
          Cancelar
        </button>
      </div>
    </form>
  </div>
</div>

// mangacount.client/src/components/AddEntryModal.jsx
import { useState, useEffect } from 'react';
import './AddEntryModal.css';

const AddEntryModal = ({ 
    isOpen, 
    onClose, 
    mangas, 
    onSuccess, 
    editEntry = null,
    selectedProfile // Add this prop
}) => {
    const [formData, setFormData] = useState({
        mangaId: '',
        quantity: '',
        pending: '',
        priority: false
    });
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [error, setError] = useState('');

    useEffect(() => {
        if (editEntry) {
            setFormData({
                mangaId: editEntry.mangaId.toString(),
                quantity: editEntry.quantity.toString(),
                pending: editEntry.pending || '',
                priority: editEntry.priority || false
            });
        } else {
            setFormData({
                mangaId: '',
                quantity: '',
                pending: '',
                priority: false
            });
        }
        setError('');
    }, [editEntry, isOpen]);

    const handleInputChange = (e) => {
        const { name, value, type, checked } = e.target;
        setFormData(prev => ({
            ...prev,
            [name]: type === 'checkbox' ? checked : value
        }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setIsSubmitting(true);
        setError('');

        if (!formData.mangaId || !formData.quantity) {
            setError('Please select a manga and enter quantity');
            setIsSubmitting(false);
            return;
        }

        try {
            const selectedManga = mangas.find(m => m.id === parseInt(formData.mangaId));
            const entryData = {
                id: editEntry ? editEntry.id : 0,
                manga: selectedManga,
                mangaId: parseInt(formData.mangaId),
                profileId: selectedProfile ? selectedProfile.id : 1, // Use selected profile
                quantity: parseInt(formData.quantity),
                pending: formData.pending || null,
                priority: formData.priority
            };

            // Always use POST - the service determines create vs update based on ID
            const response = await fetch('/api/entry', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(entryData)
            });

            if (response.ok) {
                onSuccess();
                onClose();
                if (!editEntry) {
                    setFormData({
                        mangaId: '',
                        quantity: '',
                        pending: '',
                        priority: false
                    });
                }
            } else {
                const error = await response.json();
                setError(`Failed to ${editEntry ? 'update' : 'create'} entry: ${error.message || 'Unknown error'}`);
            }
        } catch (err) {
            setError(`Error ${editEntry ? 'updating' : 'creating'} entry: ` + err.message);
        } finally {
            setIsSubmitting(false);
        }
    };

    if (!isOpen) return null;

    const isEditing = !!editEntry;

    return (
        <div className="modal-overlay">
            <div className="modal-content">
                <div className="modal-header">
                    <h2>{isEditing ? 'Edit Entry' : 'Add New Entry'}</h2>
                    <button className="close-button" onClick={onClose}>&times;</button>
                </div>
                
                <form onSubmit={handleSubmit} className="entry-form">
                    <div className="form-group">
                        <label htmlFor="mangaId">Manga *</label>
                        <select
                            id="mangaId"
                            name="mangaId"
                            value={formData.mangaId}
                            onChange={handleInputChange}
                            required
                            disabled={isEditing}
                        >
                            <option value="">Select a manga</option>
                            {mangas.map(manga => (
                                <option key={manga.id} value={manga.id}>
                                    {manga.name} {manga.volumes ? `(${manga.volumes} volumes)` : ''}
                                </option>
                            ))}
                        </select>
                        {isEditing && (
                            <small>Cannot change manga for existing entry</small>
                        )}
                    </div>

                    <div className="form-group">
                        <label htmlFor="quantity">Quantity Owned *</label>
                        <div className="quantity-input-group">
                            <input
                                type="number"
                                id="quantity"
                                name="quantity"
                                value={formData.quantity}
                                onChange={handleInputChange}
                                min="0"
                                max={editEntry?.manga?.volumes || 999}
                                required
                            />
                            {isEditing && editEntry.manga.volumes && (
                                <div className="quick-actions">
                                    <button
                                        type="button"
                                        className="quick-btn minus"
                                        onClick={() => setFormData(prev => ({
                                            ...prev,
                                            quantity: Math.max(0, parseInt(prev.quantity) - 1).toString()
                                        }))}
                                        disabled={parseInt(formData.quantity) <= 0}
                                    >
                                        -1
                                    </button>
                                    <button
                                        type="button"
                                        className="quick-btn plus"
                                        onClick={() => setFormData(prev => ({
                                            ...prev,
                                            quantity: Math.min(editEntry.manga.volumes, parseInt(prev.quantity) + 1).toString()
                                        }))}
                                        disabled={parseInt(formData.quantity) >= editEntry.manga.volumes}
                                    >
                                        +1
                                    </button>
                                </div>
                            )}
                        </div>
                        {editEntry?.manga?.volumes && (
                            <small>
                                {formData.quantity}/{editEntry.manga.volumes} volumes 
                                ({Math.round((formData.quantity / editEntry.manga.volumes) * 100)}% complete)
                            </small>
                        )}
                    </div>

                    <div className="form-group">
                        <label htmlFor="pending">Pending (optional)</label>
                        <input
                            type="text"
                            id="pending"
                            name="pending"
                            value={formData.pending}
                            onChange={handleInputChange}
                            placeholder="e.g., Volumes 5-7, Next release"
                        />
                    </div>

                    <div className="form-group checkbox-group">
                        <label htmlFor="priority">
                            <input
                                type="checkbox"
                                id="priority"
                                name="priority"
                                checked={formData.priority}
                                onChange={handleInputChange}
                            />
                            Priority item
                        </label>
                    </div>

                    {error && <div className="error-message">{error}</div>}

                    <div className="modal-actions">
                        <button type="button" onClick={onClose} className="cancel-button">
                            Cancel
                        </button>
                        <button type="submit" disabled={isSubmitting} className="submit-button">
                            {isSubmitting ? 
                                (isEditing ? 'Updating...' : 'Creating...') : 
                                (isEditing ? 'Update Entry' : 'Create Entry')
                            }
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default AddEntryModal;
